In [2]:
import numpy as np
import pandas as pd

#generation des dattaas
np.random.seed(42)

taill = 10


In [3]:
age = np.random.randint(18, 90, size=taill)

incom = np.random.randint(2000, 100000, size= taill)
laound_amout = np.random.randint(5000, 100000, size=taill)
num_accouunt = np.random.randint(1, 10, size=taill)

#creation des caracteristique input

x= np.column_stack((age, incom, laound_amout, num_accouunt)).T
x

#mecanisme de forword propagation

#fonction relu
def relu(x):
  return np.maximum(0,x)

#fonction sigmoid
def sigmoid(x):
  return 1/(1/1+np.exp(-x))



In [5]:
np.random.seed(42)
#nomvre de renone
hidden_size =5

#la taille de mes x
input_size = x.shape[0]

w1 = np.random.rand(hidden_size, input_size)
w1
#on fixe les poid alleatoire c'est nombre b1
b1= np.random.rand(hidden_size, 1)
b1

array([[0.61185289],
       [0.13949386],
       [0.29214465],
       [0.36636184],
       [0.45606998]])

In [12]:
w1

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848],
       [0.15601864, 0.15599452, 0.05808361, 0.86617615],
       [0.60111501, 0.70807258, 0.02058449, 0.96990985],
       [0.83244264, 0.21233911, 0.18182497, 0.18340451],
       [0.30424224, 0.52475643, 0.43194502, 0.29122914]])

In [15]:
output_size = 1
w2 = np.random.rand(hidden_size, output_size)
b2 = np.random.rand(hidden_size, 1)

#on vient de definir plus haut les poid et les bia

#forwoard pass notre combinaison lineaore
z1 = np.dot(w1,x)+b1
z1

#apres la couche cahe nos x se transforme en a1
a1 = relu(z1)

w2

array([[0.32518332],
       [0.72960618],
       [0.63755747],
       [0.88721274],
       [0.47221493]])

In [16]:
import numpy as np
import pandas as pd

# Génération des données
np.random.seed(42)

taille = 10
age = np.random.randint(18, 90, size=taille)
income = np.random.randint(2000, 100000, size=taille)
loan_amount = np.random.randint(5000, 100000, size=taille)
num_accounts = np.random.randint(1, 10, size=taille)

# Création des caractéristiques d'entrée
x = np.column_stack((age, income, loan_amount, num_accounts)).T
print("Input Data (x):\n", x)

# Mécanisme de forward propagation

# Fonction ReLU
def relu(x):
    return np.maximum(0, x)

# Fonction sigmoid
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

np.random.seed(42)
# Nombre de neurones dans la couche cachée
hidden_size = 5

# Taille des entrées
input_size = x.shape[0]

# Poids et biais pour la première couche cachée
w1 = np.random.rand(hidden_size, input_size)
b1 = np.random.rand(hidden_size, 1)

# Poids et biais pour la couche de sortie
output_size = 1
w2 = np.random.rand(output_size, hidden_size)
b2 = np.random.rand(output_size, 1)

# Forward pass : combinaison linéaire
z1 = np.dot(w1, x) + b1
print("\nAfter first layer (z1):\n", z1)

# Appliquer la fonction d'activation ReLU
a1 = relu(z1)
print("\nAfter ReLU activation (a1):\n", a1)

# Forward pass pour la couche de sortie
z2 = np.dot(w2, a1) + b2
print("\nAfter second layer (z2):\n", z2)

# Appliquer la fonction d'activation sigmoid
output = sigmoid(z2)
print("\nFinal output after sigmoid activation:\n", output)


Input Data (x):
 [[   69    32    89    78    38    41    20    39    70    19]
 [61735 64955 66925 69969  7311 85104 55707 87305 30693 73932]
 [98016 30658 89478 23431  7747 64150 70725 89654 40773 72435]
 [    7     4     9     3     5     3     7     5     9     7]]

After first layer (z1):
 [[130470.11163729  84210.10981154 129163.24273171  83703.5013134
   12639.26703121 127884.76567313 104744.00666645 148646.50959023
   59058.08078369 123322.11000115]
 [ 15340.41305631  11921.94824523  15658.95946126  12290.64518637
    1600.84876457  17010.95616584  12807.27331465  18837.08486485
    7175.03931562  15749.44040595]
 [ 45779.02883256  46647.3411813   49292.13721896  50075.53432678
    5364.17075793  61608.15155952  40919.5412642   63692.34383545
   22623.26260036  53858.76236477]
 [ 30989.59971912  19394.61492313  30556.23379536  19183.34314303
    2993.92546387  29770.02604515  24706.64469051  34873.35031514
   13991.16169927  28886.6132339 ]
 [ 74756.84864277  47339.48113652  73

In [17]:
import numpy as np

# Génération des données
np.random.seed(42)

taille = 10
age = np.random.randint(18, 90, size=taille)
income = np.random.randint(2000, 100000, size=taille)
loan_amount = np.random.randint(5000, 100000, size=taille)
num_accounts = np.random.randint(1, 10, size=taille)

# Création des caractéristiques d'entrée
x = np.column_stack((age, income, loan_amount, num_accounts)).T

# Normalisation des données
x = (x - np.mean(x, axis=1, keepdims=True)) / np.std(x, axis=1, keepdims=True)

# Mécanisme de forward propagation

# Fonction ReLU
def relu(x):
    return np.maximum(0, x)

# Fonction sigmoid
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

np.random.seed(42)
# Nombre de neurones dans la couche cachée
hidden_size = 5

# Taille des entrées
input_size = x.shape[0]

# Poids et biais pour la première couche cachée
w1 = np.random.randn(hidden_size, input_size) * 0.01
b1 = np.zeros((hidden_size, 1))

# Poids et biais pour la couche de sortie
output_size = 1
w2 = np.random.randn(output_size, hidden_size) * 0.01
b2 = np.zeros((output_size, 1))

# Forward pass : combinaison linéaire
z1 = np.dot(w1, x) + b1
print("\nAfter first layer (z1):\n", z1)

# Appliquer la fonction d'activation ReLU
a1 = relu(z1)
print("\nAfter ReLU activation (a1):\n", a1)

# Forward pass pour la couche de sortie
z2 = np.dot(w2, a1) + b2
print("\nValues of z2 before sigmoid:\n", z2)

# Appliquer la fonction d'activation sigmoid
output = sigmoid(z2)
print("\nFinal output after sigmoid activation:\n", output)



After first layer (z1):
 [[ 0.02052105 -0.02374211  0.03691928 -0.02314933 -0.01687683 -0.02291055
   0.00461815 -0.0035058   0.02442853  0.00369762]
 [ 0.02288704 -0.02057579  0.02307245 -0.03311236 -0.02396151 -0.00925103
   0.01378548  0.01157517  0.00262061  0.01295996]
 [-0.01212204  0.01311307 -0.01793881  0.00848305 -0.0001515   0.01298696
   0.00046857  0.00550932 -0.01500436  0.00465574]
 [-0.02496031  0.01581505 -0.02752058  0.02325632  0.07460063 -0.01672177
  -0.00910509 -0.03890821  0.02875758 -0.0252136 ]
 [-0.02755461  0.02938255 -0.0461278   0.01924517  0.0193789   0.02464533
   0.000984    0.00464577 -0.02795223  0.00335293]]

After ReLU activation (a1):
 [[0.02052105 0.         0.03691928 0.         0.         0.
  0.00461815 0.         0.02442853 0.00369762]
 [0.02288704 0.         0.02307245 0.         0.         0.
  0.01378548 0.01157517 0.00262061 0.01295996]
 [0.         0.01311307 0.         0.00848305 0.         0.01298696
  0.00046857 0.00550932 0.         0